INSERT INTO CUSTOMERMODEL (ID, VAL,FIRST_NAME,LAST_NAME) VALUES (1234, 33.50 ,'Mr. Will','Smith');
INSERT INTO CUSTOMERMODEL (ID, VAL,FIRST_NAME,LAST_NAME) VALUES (1235, 2.50 ,'Mr. Jane','Smith');


INSERT INTO STATIONMODEL (STATION_CODE, STATION_NAME,ZONES,STATION_TYPE) VALUES ('HB', 'Holborn tube station' ,'1','T');
INSERT INTO STATIONMODEL (STATION_CODE, STATION_NAME,ZONES,STATION_TYPE) VALUES ('EC', 'Earl’s Court tube station' ,'1,2','T');
INSERT INTO STATIONMODEL (STATION_CODE, STATION_NAME,ZONES,STATION_TYPE) VALUES ('WB', 'Wimbledon' ,'3','T');
INSERT INTO STATIONMODEL (STATION_CODE, STATION_NAME,ZONES,STATION_TYPE) VALUES ('HS', 'Hammersmith tube station' ,'2','T');
INSERT INTO STATIONMODEL (STATION_CODE, STATION_NAME,ZONES,STATION_TYPE) VALUES ('BS', 'Any bus station' ,null,'B');


INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('1N-Z1', 2.50);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('1N', 2.00);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('2N-Z1', 3.00);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('2N', 2.25);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('3N-Z1', 3.20);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('3N', 3.20);
INSERT INTO FAREMODEL (FARECODE, FARE) VALUES ('BS', 1.80);


