CREATE TABLE CUSTOMERMODEL
(
	ID VARCHAR2(50) NOT NULL,
	VAL VARCHAR2(50) NOT NULL,
	FIRST_NAME  VARCHAR2(50) NOT NULL,
	LAST_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE STATIONMODEL
(
	STATION_CODE VARCHAR2(2) NOT NULL,
	STATION_NAME VARCHAR2(50) NOT NULL,
	ZONES VARCHAR2(50) ,
	STATION_TYPE VARCHAR2(1) NOT NULL
);

CREATE TABLE FAREMODEL
(
	FARECODE VARCHAR2(50) NOT NULL,
	FARE VARCHAR2(50) NOT NULL
);

CREATE TABLE JOURNEYMODEL
(
	ID VARCHAR2(50) NOT NULL,
	CARD_NUMBER VARCHAR2(50) NOT NULL,
	ORIGIN VARCHAR2(50) NOT NULL,
	DESTINATION VARCHAR2(50) ,
	EXECUTION_TIME TIMESTAMP (6)
);

 CREATE SEQUENCE  "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 ;
